In [1]:
%autoreload 2
import matplotlib
matplotlib.use('TkAgg')
import BPV
import pattern_manipulation as pm
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = BPV.Data()
data.read_csv("p.delviva.csv",False)
data.df.sort_index(by="p",inplace=True,ascending=False)
data.df.set_index(pd.Index([j for j in range(len(data.df))]), inplace=True)
data_head = data.data_head(15)
#data.df.sort_index(by="p")
N=5
W=0.025  #rate
data_head.df#.head()

       pattern         p  plog1onp
0            1  0.727688  0.231319
1   1000000000  0.225095  0.335669
2          101  0.004802  0.025635
3      1000001  0.004633  0.024901
4           10  0.004063  0.022370
5    100000001  0.003980  0.021993
6    111000000  0.003585  0.020188
7         1000  0.003502  0.019802
8    111000001  0.003476  0.019679
9    111111100  0.003453  0.019575
10   100000000  0.003385  0.019257
11   111111111  0.003328  0.018987
12     1001010  0.003122  0.018013
13   100100101  0.002963  0.017249
14     1000000  0.002925  0.017065

In [3]:
prbl = BPV.BPV("decgraph",data_head,N,W,time_solver=False)
prbl.solve()
prbl.pprint_solution()

Solver =  decgraph
Entropy =  0.115086077447
Cardinality =  5
Rate =  0.0210622176202

      pattern         p  plog1onp  decgraph
2        101  0.004802  0.025635         1
3    1000001  0.004633  0.024901         1
4         10  0.004063  0.022370         1
5  100000001  0.003980  0.021993         1
6  111000000  0.003585  0.020188         1

In [4]:
prbl = BPV.BPV("pulp",data_head,N,W,time_solver=False)
prbl.solve()
prbl.pprint_solution()

Solver =  pulp
Entropy =  0.11508607744677295
Cardinality =  5
Rate =  0.0210622176202

      pattern         p  plog1onp  decgraph  pulp
2        101  0.004802  0.025635         1     1
3    1000001  0.004633  0.024901         1     1
4         10  0.004063  0.022370         1     1
5  100000001  0.003980  0.021993         1     1
6  111000000  0.003585  0.020188         1     1

In [5]:
prbl = BPV.BPV("euristic",data_head,N,W,time_solver=False)
prbl.solve()
prbl.pprint_solution()
#data_head.df[data_head.df['euristic'] != 0]
#data_head.df

Solver =  euristic
Entropy =  0.115086077447
Cardinality =  5
Rate =  0.0210622176202

      pattern         p  plog1onp  decgraph  pulp  euristic
2        101  0.004802  0.025635         1     1         1
3    1000001  0.004633  0.024901         1     1         1
4         10  0.004063  0.022370         1     1         1
5  100000001  0.003980  0.021993         1     1         1
6  111000000  0.003585  0.020188         1     1         1

In [153]:
data_head.df

       pattern         p  plog1onp  decgraph  pulp  euristic
0            1  0.727688  0.231319         0     0         0
1   1000000000  0.225095  0.335669         0     0         0
2          101  0.004802  0.025635         1     1         1
3      1000001  0.004633  0.024901         1     1         1
4           10  0.004063  0.022370         1     1         1
5    100000001  0.003980  0.021993         1     1         1
6    111000000  0.003585  0.020188         1     1         1
7         1000  0.003502  0.019802         0     0         0
8    111000001  0.003476  0.019679         0     0         0
9    111111100  0.003453  0.019575         0     0         0
10   100000000  0.003385  0.019257         0     0         0
11   111111111  0.003328  0.018987         0     0         0
12     1001010  0.003122  0.018013         0     0         0
13   100100101  0.002963  0.017249         0     0         0
14     1000000  0.002925  0.017065         0     0         0

In [94]:
ds['puppo'] = pd.Series(np.random.normal(10,1,len(ds)))
#ds['puppo'] = 1
#ds.loc[0]['puppo'] = 1

In [62]:
ds

        pattern         p  plog1onp  puppo
0             1  0.661722  0.273231    NaN
511  1000000000  0.204690  0.324691    NaN
4           101  0.004366  0.023726    NaN
64      1000001  0.004213  0.023044    NaN
1            10  0.003695  0.020693    NaN
256   100000001  0.003619  0.020343    NaN
447   111000000  0.003260  0.018668    NaN
7          1000  0.003185  0.018310    NaN
448   111000001  0.003161  0.018196    NaN
507   111111100  0.003140  0.018099    NaN
255   100000000  0.003078  0.017804    NaN
510   111111111  0.003026  0.017553    NaN
73      1001010  0.002839  0.016650    NaN
292   100100101  0.002694  0.015941    NaN
63      1000000  0.002660  0.015771    NaN
504   111111001  0.002606  0.015504    NaN
219    11011100  0.002415  0.014552    NaN
438   110110111  0.002317  0.014056    NaN
6           111  0.001694  0.010811    NaN
192    11000001  0.001643  0.010533    NaN
36       100101  0.001579  0.010186    NaN
72      1001001  0.001503  0.009769    NaN
3           100  0.001495  0.009723    NaN
384   110000001  0.001488  0.009690    NaN
439   110111000  0.001305  0.008666    NaN
319   101000000  0.001304  0.008663    NaN
8          1001  0.001298  0.008630    NaN
32       100001  0.001288  0.008573    NaN
475   111011100  0.001282  0.008540    NaN
505   111111010  0.001264  0.008437    NaN
..          ...       ...       ...    ...
277   100010110  0.000006  0.000067    NaN
106     1101011  0.000005  0.000064    NaN
369   101110010  0.000005  0.000064    NaN
85      1010110  0.000005  0.000064    NaN
339   101010100  0.000005  0.000064    NaN
227    11100100  0.000005  0.000064    NaN
42       101011  0.000005  0.000062    NaN
168    10101001  0.000005  0.000062    NaN
156    10011101  0.000005  0.000059    NaN
174    10101111  0.000005  0.000056    NaN
138    10001011  0.000005  0.000056    NaN
325   101000110  0.000005  0.000056    NaN
469   111010110  0.000005  0.000056    NaN
172    10101101  0.000004  0.000053    NaN
229    11100110  0.000004  0.000053    NaN
142    10001111  0.000004  0.000050    NaN
337   101010010  0.000004  0.000050    NaN
163    10100100  0.000004  0.000050    NaN
349   101011110  0.000004  0.000047    NaN
394   110001011  0.000004  0.000047    NaN
117     1110110  0.000004  0.000047    NaN
405   110010110  0.000004  0.000047    NaN
234    11101011  0.000003  0.000041    NaN
285   100011110  0.000003  0.000039    NaN
348   101011101  0.000003  0.000039    NaN
340   101010101  0.000003  0.000036    NaN
169    10101010  0.000003  0.000036    NaN
398   110001111  0.000003  0.000033    NaN
170    10101011  0.000002  0.000030    NaN
341   101010110  0.000002  0.000027    NaN

[512 rows x 4 columns]

In [65]:
v = ds[['p','plog1onp']]

v

            p  plog1onp
0    0.661722  0.273231
511  0.204690  0.324691
4    0.004366  0.023726
64   0.004213  0.023044
1    0.003695  0.020693
256  0.003619  0.020343
447  0.003260  0.018668
7    0.003185  0.018310
448  0.003161  0.018196
507  0.003140  0.018099
255  0.003078  0.017804
510  0.003026  0.017553
73   0.002839  0.016650
292  0.002694  0.015941
63   0.002660  0.015771
504  0.002606  0.015504
219  0.002415  0.014552
438  0.002317  0.014056
6    0.001694  0.010811
192  0.001643  0.010533
36   0.001579  0.010186
72   0.001503  0.009769
3    0.001495  0.009723
384  0.001488  0.009690
439  0.001305  0.008666
319  0.001304  0.008663
8    0.001298  0.008630
32   0.001288  0.008573
475  0.001282  0.008540
505  0.001264  0.008437
..        ...       ...
277  0.000006  0.000067
106  0.000005  0.000064
369  0.000005  0.000064
85   0.000005  0.000064
339  0.000005  0.000064
227  0.000005  0.000064
42   0.000005  0.000062
168  0.000005  0.000062
156  0.000005  0.000059
174  0.000005  0.000056
138  0.000005  0.000056
325  0.000005  0.000056
469  0.000005  0.000056
172  0.000004  0.000053
229  0.000004  0.000053
142  0.000004  0.000050
337  0.000004  0.000050
163  0.000004  0.000050
349  0.000004  0.000047
394  0.000004  0.000047
117  0.000004  0.000047
405  0.000004  0.000047
234  0.000003  0.000041
285  0.000003  0.000039
348  0.000003  0.000039
340  0.000003  0.000036
169  0.000003  0.000036
398  0.000003  0.000033
170  0.000002  0.000030
341  0.000002  0.000027

[512 rows x 2 columns]